build:
  stage: build
  image: golang
  script:
    - CGO_ENABLED=0 go build
    - REDIRECT_URL="http://127.0.0.1:8080/oauth-authorized" ./status &
    - sleep 5
    - curl -f http://127.0.0.1:8080/ | grep "login"
    - curl -f http://127.0.0.1:8080/login | grep "$GITLAB_URL"
  artifacts:
    expire_in: 1w
    paths:
      - status

docker:
  stage: test
  image: docker
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest

deploy:
  stage: deploy
  tags:
    - ansible
  script:
    - ansible-playbook -i $STATUS_HOST, deploy.yml
  dependencies:
    - build
  environment:
    name: status
    url: https://$STATUS_URL
  only:
    - master

